config/routes.rb
Rails.application.routes.draw do

  resource :session, only: [:new, :create, :destroy], controller: 'session'
  resource :user, only: [:new, :create, :show], controller: 'user'
  resource :group, only: [:new, :create, :show], controller: 'group' do
    member do
      get :teach
    end
  end

  resource :time_spent, only: [:new, :create, :show], controller: 'time_spent' do
    member do
      get :plancheckshow
      get :planchecknew
    end
  end
  
  root "session#new"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_alert.html.erb
<div>
    <div>
      <%= flash[:alert] %>
    </div>
</div>

app/views/shared/_groupview.html.erb
<% @grp.each do |g| %>
    <div class="bgcolor-white h-100-px m-10">
        <div class="p-20 color-darkgray d-flex ai-center ">
            <div class="pr-40"> 
                <i class="<%= g.Icon %> fa-3x color-blue"></i>
            </div>
            <div class="d-flex-c">
                <div class="pb-10"><%= g.name %></div>
                <div class="pb-10"><%= g.created_at.strftime('%d %b %Y') %></div>
                <%= link_to 'Click here', teach_group_path(:group_id => g.id), class: 'color-blue' %>    
            </div>
            
            
            
        </div>
    </div>
<%end%>

app/views/shared/_notice.html.erb
<div>
    <div>
      <%= flash[:notice] %>
    </div>
</div>

app/views/shared/_warning.html.erb
<div>
    <div>
      <%= flash[:warning] %>
    </div>
</div>