config/routes.rb
Rails.application.routes.draw do

  resource :session, only: [:new, :create, :destroy], controller: 'session'
  resource :user, only: [:new, :create, :show], controller: 'user'
  resource :group, only: [:new, :create, :show], controller: 'group' do
    member do
      get :teach
    end
  end

  resource :time_spent, only: [:new, :create, :show], controller: 'time_spent' do
    member do
      get :plancheckshow
      get :planchecknew
    end
  end
  
  root "session#new"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/time_spent.rb
class TimeSpent < ApplicationRecord
  validates :name, presence: true, length: { minimum: 5 }
  validates :Amount, presence: true
  validates :Amount,
            numericality: { only_integer: true, greater_than_or_equal_to: 60, less_than_or_equal_to: 720,
                            message: 'Mins should be greater than 60 or less than 720' }

  belongs_to :author, class_name: 'User'
  has_many :group_times, dependent: :destroy
  has_many :groups, through: :group_times

  def get_name(userid)
    @usr = User.select('name').where(id: userid).take
    @usr
  end

  def create_gt(gids)
    gids.each do |g|
      gt = group_times.build(group_id: g)
      gt.save
    end
  end
end

app/controllers/time_spent_controller.rb
# rubocop:disable Metrics/PerceivedComplexity
class TimeSpentController < ApplicationController
  before_action :current_user_exist?, include: %i[new new2 create create2 show show2]

  def new
    @tss = TimeSpent.new
    @grp = Group.all
  end

  def create
    if params[:loghrs][:group_id] == [''] && params[:loghrs][:withgrp]
      redirect_to new_time_spent_path, notice: 'Please select Grade(s)'
    else
      @tss = current_user.time_spents.build(name: params[:loghrs][:name], Amount: params[:loghrs][:amount].to_i)
      respond_to do |format|
        if @tss.save
          if !params[:loghrs][:group_id].nil?
            @tss.create_gt(params[:loghrs][:group_id])
            format.html { redirect_to time_spent_path, notice: 'time_spent Entry successfully created!!' }
          else
            format.html { redirect_to plancheckshow_time_spent_path, notice: 'plan_check Entry successfully created!!' }
          end
        else
          format.html { redirect_to new_time_spent_path, alert: @tss.errors.full_messages }
        end
      end
    end
  end

  def planchecknew
    @ts2 = TimeSpent.new
  end

  def show
    @ts = current_user.time_spents.where('id IN (?)', GroupTime.select('time_spent_id')).last
    @grp = @ts.groups unless @ts.nil?
  end

  def plancheckshow
    @ts = current_user.time_spents.where('id NOT IN (?)', GroupTime.select('time_spent_id')).order(created_at: :desc)
  end

  private

  def timespent_params
    params.require(:loghrs).permit(:name, :amount, :group_id, :withgrp)
  end
end
# rubocop:enable Metrics/PerceivedComplexity

app/helpers/time_spent_helper.rb
module TimeSpentHelper
  def show_timespent
    content = ''

    unless @ts.nil?
      content << "<div class='d-inline'>#{@ts.created_at.strftime('%d %b %Y')}</div>
      <div class='d-inline pl-5'>#{@ts.name}</div>
      <div class='float-r'>Total:#{time_in_hrs(@ts.Amount)} </div>"
    end
    content.html_safe
  end

  def render_grpview
    content = ''
    content << "<div> #{render 'shared/groupview'} </div>" unless @ts.nil?
    content.html_safe
  end
end

app/views/time_spent/new.html.erb
<div class="bgcolor-white">
  <div class="m-10 pt-10 pb-10">
    <h2 class="color-darkgray caps txt-center m-10">Log Working Hours</h2>
      <div>
        <%= form_with model: @time_spent, scope: "loghrs", url: time_spent_path, validate: true, class: ' color-darkgray ' do |f| %>
          <div>
            <%= f.label :name, "Subject" %>
            
            <%= f.select(:name, options_for_select([['Science'], ['Maths'], ['Physical Education'], ['Arts & Crafts']])) %>
            
            <br><br>
            <%= f.label :amount, "Duration(mins)" %>
            <%= f.text_field :amount, class: "w-120-px" %> <br><br>
            
            <ul>
                <%= f.collection_check_boxes :group_id, @grp, :id, :name do |b| %> 
                      <li class="m-10 p-10"><%= b.label { b.check_box + b.text } %> </li>
                        <% end %>
            </ul>
              <%= f.hidden_field :withgrp, :value => true %>
            <br><br>
            <div class="bgcolor-green h-50-px txt-center"><%= f.submit "Submit", class: "caps border-w-1px border-white border-solid m-10 pl-40 pr-40  pt-5 pb-5 color-gray bgcolor-green" %></div>
            </div>
        <% end %>
      </div>
  </div>
</div>

app/views/time_spent/new2.html.erb
<div class="bgcolor-white">
  <div class="m-10 pt-10 pb-10">
    <h2 class="color-darkgray caps txt-center m-10">Log Working Hours</h2>
      <div>
        <%= form_with model: @time_spent, scope: "loghrs", class: ' color-darkgray ' do |f| %>
          <div>
            <%= f.label :name, "Task" %>
            <%#= f.text_field :name %>
            <%= f.select(:name, options_for_select([['Planning'], ['Checking'], ['Teacher Training']])) %>
             <br><br>
            <%= f.label :amount, "Duration(mins)" %>
            <%= f.text_field :amount, class: "w-120-px" %> <br><br>
          
            <div class="txt-center bgcolor-green h-50-px"><%= f.submit "Submit", class: "caps border-w-1px border-white border-solid m-10 pl-40 pr-40  pt-5 pb-5 color-gray bgcolor-green" %></div>
            </div>
        <% end %>
      </div>
  </div>
</div>

app/views/time_spent/planchecknew.html.erb
<div class="bgcolor-white">
  <div class="m-10 pt-10 pb-10">
    <h2 class="color-darkgray caps txt-center m-10">Log Working Hours</h2>
      <div>
        <%= form_with model: @time_spent, scope: "loghrs", url: time_spent_path, class: ' color-darkgray ' do |f| %>
          <div>
            <%= f.label :name, "Task" %>
            <%#= f.text_field :name %>
            <%= f.select(:name, options_for_select([['Planning'], ['Checking'], ['Teacher Training']])) %>
             <br><br>
            <%= f.label :amount, "Duration(mins)" %>
            <%= f.text_field :amount, class: "w-120-px" %> <br><br>
              <%= f.hidden_field :withgrp, :value => false %>
            <div class="txt-center bgcolor-green h-50-px"><%= f.submit "Submit", class: "caps border-w-1px border-white border-solid m-10 pl-40 pr-40  pt-5 pb-5 color-gray bgcolor-green" %></div>
            </div>
        <% end %>
      </div>
  </div>
</div>

app/views/time_spent/plancheckshow.html.erb
<% @ts.each do |t| %>
    <div class="bgcolor-white h-100-px m-10">
        <div class="p-20 color-darkgray d-flex ai-center ">
            
            <div class="d-flex-c">
                <div class="pb-10"><%= t.name %></div>
                <div><%= t.created_at.strftime('%d %b %Y') %></div>
            </div>
            
            <div class="pl-40"> 
                <%= time_in_hrs(t.Amount) %>
            </div>
            
        </div>
    </div>
<%end%>

<div class="bgcolor-green h-50-px  txt-center pt-5 pb-5 m-10">
   <div class="m-10 border-w-1px border-white border-solid bgcolor-green pt-5 pb-5">
      <%= link_to 'Log Planning/Checking Hours', planchecknew_time_spent_path, class:' caps  '%>       
   </div>
</div>

app/views/time_spent/show.html.erb
<div class="bgcolor-white h-50-px">
    <div class="p-20 color-darkgray">
          <%= show_timespent %>
            
    </div>
</div>
 
<%= render_grpview %> 

<div class="bgcolor-green h-50-px  txt-center pt-5 pb-5 m-10">
   <div class="m-10 border-w-1px border-white border-solid bgcolor-green pt-5 pb-5">
      <%= link_to 'Log Teaching Hours', new_time_spent_path, class:' caps  '%>       
   </div>
</div>

app/views/time_spent/show2.html.erb
<% @ts.each do |t| %>
    <div class="bgcolor-white h-100-px m-10">
        <div class="p-20 color-darkgray d-flex ai-center ">
            
            <div class="d-flex-c">
                <div class="pb-10"><%= t.name %></div>
                <div><%= t.created_at.strftime('%d %b %Y') %></div>
            </div>
            
            <div class="pl-40"> 
                <%= time_in_hrs(t.Amount) %>
            </div>
            
        </div>
    </div>
<%end%>

<div class="bgcolor-green h-50-px  txt-center pt-5 pb-5 m-10">
   <div class="m-10 border-w-1px border-white border-solid bgcolor-green pt-5 pb-5">
      <%= link_to 'Log Planning/Checking Hours', time_spent_plan_check_new_path, class:' caps  '%>       
   </div>
</div>