config/routes.rb
Rails.application.routes.draw do

  resource :session, only: [:new, :create, :destroy], controller: 'session'
  resource :user, only: [:new, :create, :show], controller: 'user'
  resource :group, only: [:new, :create, :show], controller: 'group' do
    member do
      get :teach
    end
  end

  resource :time_spent, only: [:new, :create, :show], controller: 'time_spent' do
    member do
      get :plancheckshow
      get :planchecknew
    end
  end
  
  root "session#new"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { minimum: 5 }
  validates_uniqueness_of :name, on: :create, message: 'This name is already taken!'

  has_many :time_spents, dependent: :destroy, foreign_key: 'author_id'
  has_many :groups, dependent: :destroy
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :current_user_exist?, only: [:show]

  def def(_new)
    @user = User.new
  end

  def create
    @user = User.create(user_params)

    respond_to do |format|
      if @user.save
        session_var(format)

      elsif @user.errors.any?
        format.html { redirect_to new_user_path, alert: @user.errors.full_messages }
      else
        format.html { redirect_to new_user_path, alert: 'Invalid name!!' }

      end
    end
  end

  def show
    @user = User.find_by(id: session[:current_user_id])
    @total_hrs = @user.time_spents.sum('Amount')
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/new.html.erb
<div class="bgcolor-white">
  <div class="m-10 pt-10 pb-10">
    <h2 class="color-darkgray caps txt-center m-10">Register</h2>
    
      <div>
        <%= form_with model: @user, scope: "user", url: user_path, class: ' color-darkgray txt-center' do |f| %>
          <div>
            <%= f.label :name %>
            <%= f.text_field :name %> <br><br>
            <div class="bgcolor-green h-50-px"><%= f.submit "Register", class: "caps border-w-1px border-white border-solid m-10 pl-40 pr-40  pt-5 pb-5 color-gray bgcolor-green" %></div>
          </div>
        <% end %>
      </div>
  </div>
</div>

app/views/user/show.html.erb
<body class="bgcolor-blue">

<div class="m-10 pt-10 pb-10 txt-center">
 <p class="color-gray caps bgcolor-green p-20">Total Hours: <%= time_in_hrs(@total_hrs) %></p>
 
</div>

<div class="bgcolor-blue">
    <div class="m-10 pt-10 pb-10">
            <ul class="p-20">
                <li class="p-20"><%= link_to 'Hours Logged for Teaching', time_spent_path %></li>
                <li class="p-20"><%= link_to 'Hours Logged for planning/checking', plancheckshow_time_spent_path %></li>
                <li class="p-20"><%= link_to 'All Grades', group_path %></li>
                
            </ul>
    </div>
</div>
</body>